CREATE DATABASE [TOLEDO_PRUEBAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TOLEDO_PRUEBAS', FILENAME = N'C:\Users\A117665\TOLEDO_PRUEBAS.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TOLEDO_PRUEBAS_log', FILENAME = N'C:\Users\A117665\TOLEDO_PRUEBAS_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET ARITHABORT OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET  READ_WRITE 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET  MULTI_USER 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TOLEDO_PRUEBAS] SET DELAYED_DURABILITY = DISABLED 
GO
USE [TOLEDO_PRUEBAS]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [TOLEDO_PRUEBAS]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [TOLEDO_PRUEBAS] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [TOLEDO_PRUEBAS]
GO

/****** Object:  Table [dbo].[Usuario]    Script Date: 03/07/2020 12:57:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuario](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nif] [nvarchar](50) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Descripcion] [nvarchar](50) NOT NULL,
	[FechaDeAlta] [datetime] NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO [dbo].[Usuario]([Nif],[Nombre],[Descripcion],[FechaDeAlta]) VALUES ('04170001K', 'Rafael Castro Gómez', 'Usuario administrador', (GETDATE()))
GO
INSERT INTO [dbo].[Usuario]([Nif],[Nombre],[Descripcion],[FechaDeAlta]) VALUES ('04100000B', 'María López Santiago', 'Usuario genérico', (GETDATE()))
GO
INSERT INTO [dbo].[Usuario]([Nif],[Nombre],[Descripcion],[FechaDeAlta]) VALUES ('04170001K', 'José López Cano', 'Usuario genérico', (GETDATE()))
